// import { APP_CONFIG } from '@/utils/env'
export const SET_LOADING = 'SET_LOADING'
export const STATUS_FAIL = 'STATUS_FAIL'
export const LIST_COMMENT = 'LIST_COMMENT'
export const GET_CONTENT_CONFIG = 'GET_CONTENT_CONFIG'
export const GET_LIST_PROVINCE = 'GET_LIST_PROVINCE'
export const GET_RATE_ARTICLES = 'GET_RATE_ARTICLES'
